### ISSUE TITLE
calculating flops for video models whch has more complated input

### ISSUE THREAD

**Issue by TonyAlbertWan** [zugexiaodui/torch_flops#9]
在计算例如VideoMAE的GFLOPs的时候，模型输入如下：
```
output = model(video, mask_embed)
# video : tensor.shape(1,3,16,224,224)
# mask_embed : tensor.shape(1, 1568)
```
这两个输入在不修改model本身的前提下没办法先合并再拆分；
但torch_flops代码中写到的模型输入仅有x一个：
```x = torch.randn([B, N, C]).to(device)```
请问如何修改代码才能计算这种包含复杂输入的操作呢？

**Comment by zugexiaodui** [comment]
你好，本库可以支持多个输入，不需要做修改，直接使用`flops_counter.propagate(x1, x2)`即可。

**Comment by TonyAlbertWan** [comment]
感谢！我去尝试一下！

**Comment by TonyAlbertWan** [comment]
我分别在python3.8&torch1.10和py3.10&torch2.0.0的版本下都测试了自己的代码以及给出的example代码，都得到如下报错：
```
Traceback (most recent call last):
  File "/data/VideoMAE/flops.py", line 10, in <module>
    from torch_flops import TorchFLOPsByFX
  File "/data/anaconda3/envs/otter/lib/python3.9/site-packages/torch_flops/__init__.py", line 1, in <module>
    from .flops_engine import TorchFLOPsByFX
  File "/data/anaconda3/envs/otter/lib/python3.9/site-packages/torch_flops/flops_engine.py", line 15, in <module>
    from torch_flops.flops_ops import MODULE_FLOPs_MAPPING, METHOD_FLOPs_MAPPING, FUNCTION_FLOPs_MAPPING
  File "/data/anaconda3/envs/otter/lib/python3.9/site-packages/torch_flops/flops_ops.py", line 93, in <module>
    def ModuleFLOPs_ConvNd(module: nn.Conv1d | nn.Conv2d | nn.Conv3d, result: Tensor, *args, **kwargs) -> int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
上面的"/data/VideoMAE/flops.py"就是example1.py的运行结果
是哪个环境出现问题了吗？

**Comment by zugexiaodui** [comment]
`TypeError: unsupported operand type(s) for |: 'type' and 'type'` 是python版本过低不支持`|`引起的，但是升级到python3.10应该就可以了。你这两个环境报的错误都是这一个吗？
